name: Multi-Platform Build & Release

on:
  push:
    tags:
      - 'v*' # 触发规则：当推送以v开头的tag时执行

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, windows]
        arch: [x64, arm64]
        include:
          - platform: linux
            arch: x64
            ext: linux-x64
          - platform: linux
            arch: arm64
            ext: linux-arm64
          - platform: windows
            arch: x64
            ext: windows-x64.exe
          - platform: windows
            arch: arm64
            ext: windows-arm64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
        shell: shell

      - name: Verify Bun installation
        run: bun --version
        shell: shell

      - name: Install dependencies
        run: bun install

      - name: Build for ${{ matrix.platform }}/${{ matrix.arch }}
        run: |
          bun build --minify --compile remote-ssh.ts \
            --target ${{ matrix.platform }}-${{ matrix.arch }} \
            --outfile dist/${{ github.ref_name }}/remote-ssh-${{ matrix.ext }}
        env:
          NODE_ENV: production
        shell: bash

      - name: Package binaries for Linux
        if: matrix.platform == 'linux'
        run: |
          mkdir -p dist/assets
          cd dist/${{ github.ref_name }}

          # 创建平台专属压缩包
          tar czf ../../assets/remote-ssh-${{ matrix.ext }}.tar.gz \
            --transform 's,^,linux/,' \
            remote-ssh-${{ matrix.ext }}
        shell: bash

      - name: Package binaries for Windows
        if: matrix.platform == 'windows'
        run: |
          mkdir -p dist/assets
          cd dist/${{ github.ref_name }}

          # 确保7z已安装
          if ! command -v 7z &> /dev/null; then
            echo "Installing 7z..."
            sudo apt-get update && sudo apt-get install -y p7zip-full
          fi

          # 创建平台专属压缩包
          7z a ../../assets/remote-ssh-${{ matrix.ext }}.zip remote-ssh-${{ matrix.ext }}
        shell: bash

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/assets/*
